name: cp4

channels:
  - conda-forge
  - anaconda
  - bioconda
  - defaults

dependencies:
  - python=3.8
  - numpy
  - matplotlib
  - pandas
  - mysqlclient=1.4
  - openjdk
  - gtk2
  - wxpython
  - pip:
    - cellprofiler
